version: '3'

services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=movie_management_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    networks:
      - app-network

  # Nginx for Laravel Backend
  backend-nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  # Angular Frontend
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend-nginx
    networks:
      - app-network
    
  # MySQL Database
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=movie_management_db
      - MYSQL_PASSWORD=movie_pass
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: